webtalk_init -webtalk_dir C:/Users/dzial/Documents/Mikroelektronika_AGH/mgr/1_semestr/systemy_dedykowane_w_ukladach_programowalnych/1_lab/SDUP_laboratory/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/cordic_rtl_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar 13 14:40:19 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1971d9fe-df7c-44f2-a346-09c76c4ad1e7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5dab97a6b6ee49e38b318d85daef09ed" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6348_KB" -context "xsim\\usage"
webtalk_transmit -clientid 504264941 -regid "" -xml C:/Users/dzial/Documents/Mikroelektronika_AGH/mgr/1_semestr/systemy_dedykowane_w_ukladach_programowalnych/1_lab/SDUP_laboratory/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/cordic_rtl_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/dzial/Documents/Mikroelektronika_AGH/mgr/1_semestr/systemy_dedykowane_w_ukladach_programowalnych/1_lab/SDUP_laboratory/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/cordic_rtl_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/dzial/Documents/Mikroelektronika_AGH/mgr/1_semestr/systemy_dedykowane_w_ukladach_programowalnych/1_lab/SDUP_laboratory/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/cordic_rtl_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
