webtalk_init -webtalk_dir C:/__Programowanie__/Vivado/PrzemyslawKurzak/SDUP_2022_temp/lab_2v2/2_lab/cordic_acc.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 17 11:00:06 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2eba3350-e965-49ee-a710-5805bbacfc55" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3657f3d626674c239b953e47be18709f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "38412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4249114813 -regid "" -xml C:/__Programowanie__/Vivado/PrzemyslawKurzak/SDUP_2022_temp/lab_2v2/2_lab/cordic_acc.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/__Programowanie__/Vivado/PrzemyslawKurzak/SDUP_2022_temp/lab_2v2/2_lab/cordic_acc.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/__Programowanie__/Vivado/PrzemyslawKurzak/SDUP_2022_temp/lab_2v2/2_lab/cordic_acc.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
